version: '3.7'

services:
    foodiedb:
        image: postgres:12-alpine
        container_name: foodiedb
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        env_file: 
            - env/.db.env
    foodie:
        build:
            context: .
            dockerfile: dockerfile
        container_name: foodie
        ports:
            - "5000:5000"
        environment:
            - APP_ENV=test
        env_file:
            - env/.env
        depends_on:
            - foodiedb
        volumes:
            - .:/src/foodie/
        command: ["uvicorn", "foodie.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    foodie-pgadmin:
        container_name: foodie-pgadmin
        image: dpage/pgadmin4
        env_file: 
            - env/.pgadmin.env
        ports:
            - "5050:80"
        depends_on:
            - foodiedb


volumes: 
    postgres_data:
